import os
import sys
import json
import re
import subprocess
import pytest
from pathlib import Path

from tests.helpers import PROJECT_ROOT, SRC_DIR

if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

import patcher


def run_node_eval(script_code: str):
    """
    Safely executes a JavaScript script in Node.js via stdin to bypass
    Windows command-line length limits (WinError 206) and enforce UTF-8 encoding.
    """
    proc = subprocess.run(
        ["node"],
        input=script_code,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
    )
    if proc.returncode != 0:
        raise RuntimeError(f"Node execution failed with exit code {proc.returncode}:\n{proc.stderr}")
    return proc.stdout.strip()


class TestCssEscapingAndInjection:
    def test_raw_stylesheet_css_syntax(self):
        """
        Verify that the standalone CSS file src/antigravity-chat-rtl.css uses
        valid CSS ID selector escaping: #antigravity\\.agentSidePanelInputBox
        (with one backslash escaping the dot character).
        """
        css_file = SRC_DIR / "antigravity-chat-rtl.css"
        assert css_file.exists(), "antigravity-chat-rtl.css must exist in src/"

        css_content = css_file.read_text(encoding="utf-8")

        # Must contain #antigravity\.agentSidePanelInputBox
        matches = re.findall(r"#antigravity\\\.agentSidePanelInputBox", css_content)
        assert len(matches) >= 4, f"Expected at least 4 occurrences of #antigravity\\. in CSS, found {len(matches)}"

        # Must NOT contain unescaped #antigravity.agentSidePanelInputBox
        unescaped_matches = re.findall(r"#antigravity\.agentSidePanelInputBox", css_content)
        assert len(unescaped_matches) == 0, (
            f"Found {len(unescaped_matches)} unescaped instances of #antigravity.agentSidePanelInputBox in CSS!"
        )

    def test_python_injection_snippet_contains_escaped_selector(self):
        """
        Verify that get_injection_snippet() in patcher.py generates a JavaScript string
        with double backslashes (#antigravity\\.agentSidePanelInputBox) so that
        the template literal in dist/preload.js survives JS evaluation.
        """
        snippet = patcher.get_injection_snippet()
        assert "__ANTIGRAVITY_RTL_INJECTED__" in snippet, "Snippet must contain injection banner"
        assert "const rtlCSS = `" in snippet, "Snippet must define rtlCSS template literal"

        # In JS source code inside template literal, double backslash \\. is required:
        assert r"#antigravity\\.agentSidePanelInputBox" in snippet, (
            "Python get_injection_snippet() must contain '#antigravity\\\\.agentSidePanelInputBox' "
            "with double backslash in JavaScript template literal source."
        )

    def test_python_injection_snippet_runtime_v8_evaluation(self):
        """
        Execute Node.js to evaluate the exact JavaScript snippet generated by Python's
        get_injection_snippet() and inspect the runtime string value of rtlCSS in memory.
        """
        snippet = patcher.get_injection_snippet()

        eval_script = f"""
        const snippetCode = {json.dumps(snippet)};

        // Extract the template literal content: const rtlCSS = `...`;
        const match = snippetCode.match(/const\\s+rtlCSS\\s*=\\s*`([\\s\\S]*?)`;/);
        if (!match) {{
            console.error("Failed to find rtlCSS definition in snippet");
            process.exit(1);
        }}

        // Evaluate template literal as JavaScript would in V8
        const evaluatedRtlCss = eval('`' + match[1] + '`');

        console.log(JSON.stringify({{
            evaluatedCss: evaluatedRtlCss
        }}));
        """

        stdout = run_node_eval(eval_script)
        res = json.loads(stdout)
        evaluated_css = res.get("evaluatedCss")
        assert evaluated_css is not None, "Failed to extract evaluated rtlCSS from snippet"

        # At runtime in V8 memory:
        # 1. Must contain #antigravity\.agentSidePanelInputBox (one backslash escaping the dot)
        assert "#antigravity\\.agentSidePanelInputBox" in evaluated_css, (
            "Runtime CSS must contain single backslash before dot: '#antigravity\\.agentSidePanelInputBox'"
        )

        # 2. Must NOT contain #antigravity.agentSidePanelInputBox (zero backslashes)
        unescaped = re.findall(r"#antigravity\.agentSidePanelInputBox", evaluated_css)
        assert len(unescaped) == 0, (
            "Runtime CSS contains unescaped dot! V8 stripped the backslash during template literal evaluation."
        )

    def test_node_injection_snippet_runtime_v8_evaluation(self, tmp_path):
        """
        Verify that src/patcher.js generates an injection snippet in dist/preload.js
        with proper double backslash escaping (#antigravity\\.agentSidePanelInputBox),
        which evaluates in Node.js / V8 runtime to #antigravity\\.agentSidePanelInputBox.
        """
        from tests.helpers import create_mock_antigravity_dir

        mock_dir = tmp_path / "node_css_test"
        create_mock_antigravity_dir(mock_dir, version="2.15.0", is_patched=False)

        # Run patcher.js on mock installation
        proc = subprocess.run(
            ["node", str(SRC_DIR / "patcher.js"), "--path", str(mock_dir), "--no-kill"],
            stdin=subprocess.DEVNULL,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            check=True,
        )

        # Extract patched preload.js from the resulting app.asar
        asar_path = mock_dir / "resources" / "app.asar"
        patched_preload = patcher.extract_file_from_asar(str(asar_path), "dist/preload.js")
        assert patched_preload is not None, "dist/preload.js must be present in patched ASAR"

        # 1. In the JS template literal in dist/preload.js, double backslash must be present:
        assert r"#antigravity\\.agentSidePanelInputBox" in patched_preload, (
            "Patched preload.js from patcher.js must contain '#antigravity\\\\.agentSidePanelInputBox' "
            "with double backslash in JavaScript template literal."
        )

        # 2. Evaluate the template literal in Node.js V8 runtime:
        eval_script = f"""
        const snippetCode = {json.dumps(patched_preload)};
        const match = snippetCode.match(/const\\s+rtlCSS\\s*=\\s*`([\\s\\S]*?)`;/);
        if (!match) {{
            console.error("Failed to find rtlCSS definition in patched preload.js");
            process.exit(1);
        }}
        const evaluatedCss = eval('`' + match[1] + '`');
        console.log(JSON.stringify({{ evaluatedCss: evaluatedCss }}));
        """

        stdout = run_node_eval(eval_script)
        res = json.loads(stdout)
        evaluated_css = res.get("evaluatedCss")
        assert evaluated_css is not None, "Failed to evaluate rtlCSS from preload.js"

        # Runtime CSS must contain escaped dot:
        assert "#antigravity\\.agentSidePanelInputBox" in evaluated_css, (
            "Runtime CSS from patcher.js must contain single backslash before dot: '#antigravity\\.agentSidePanelInputBox'"
        )

        # Runtime CSS must NOT have stripped backslash:
        unescaped = re.findall(r"#antigravity\.agentSidePanelInputBox", evaluated_css)
        assert len(unescaped) == 0, (
            "Runtime CSS from patcher.js has unescaped dot (#antigravity.agentSidePanelInputBox)!"
        )

    def test_all_four_selector_rules_escaped_in_runtime_css(self):
        """
        Verify all 4 specific selector rules in the runtime CSS retain the escaped dot:
        1. body:not(.ag-rtl-disabled) #antigravity\\.agentSidePanelInputBox [contenteditable="true"]
        2. body:not(.ag-rtl-disabled) #antigravity\\.agentSidePanelInputBox [contenteditable="true"]
        3. body:not(.ag-rtl-disabled) #antigravity\\.agentSidePanelInputBox p.pointer-events-none
        4. body.ag-rtl-disabled #antigravity\\.agentSidePanelInputBox p.pointer-events-none
        """
        snippet = patcher.get_injection_snippet()

        eval_script = f"""
        const snippetCode = {json.dumps(snippet)};
        const match = snippetCode.match(/const\\s+rtlCSS\\s*=\\s*`([\\s\\S]*?)`;/);
        const evaluatedCss = match ? eval('`' + match[1] + '`') : null;
        console.log(JSON.stringify({{ evaluatedCss: evaluatedCss }}));
        """

        stdout = run_node_eval(eval_script)
        res = json.loads(stdout)
        evaluated_css = res["evaluatedCss"]

        occurrences = re.findall(r"#antigravity\\\.agentSidePanelInputBox", evaluated_css)
        assert len(occurrences) >= 4, (
            f"Expected at least 4 occurrences of escaped selector in evaluated CSS, found {len(occurrences)}"
        )
