import re
import sys
import pytest
from pathlib import Path

from tests.helpers import SRC_DIR

if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

import patcher


class TestPerformanceAndNonReflow:
    """
    Verifies that layout-thrashing synchronous .innerText reads have been completely
    eliminated in favor of non-reflow .textContent reads during DOM mutation processing,
    and that CPU-pegging spinlocks or ping loops have been eliminated.
    """

    def test_zero_inner_text_in_patcher_py(self):
        """
        Verify that src/patcher.py contains 0 instances of innerText.
        """
        py_path = SRC_DIR / "patcher.py"
        content = py_path.read_text(encoding="utf-8")

        matches = re.findall(r"\binnerText\b", content)
        assert len(matches) == 0, (
            f"Found {len(matches)} instance(s) of 'innerText' in src/patcher.py! "
            f"Direction inspection must exclusively use 'textContent' to prevent forced reflows."
        )

    def test_zero_inner_text_in_patcher_js(self):
        """
        Verify that src/patcher.js contains 0 instances of innerText.
        """
        js_path = SRC_DIR / "patcher.js"
        content = js_path.read_text(encoding="utf-8")

        matches = re.findall(r"\binnerText\b", content)
        assert len(matches) == 0, (
            f"Found {len(matches)} instance(s) of 'innerText' in src/patcher.js! "
            f"Direction inspection must exclusively use 'textContent' to prevent forced reflows."
        )

    def test_exclusive_text_content_in_patcher_py(self):
        """
        Verify that src/patcher.py uses .textContent across direction inspection points.
        """
        py_path = SRC_DIR / "patcher.py"
        content = py_path.read_text(encoding="utf-8")

        # Must have textContent calls in direction detection
        matches = re.findall(r"\.textContent\b", content)
        assert len(matches) >= 10, (
            f"Expected at least 10 occurrences of '.textContent' in src/patcher.py, found {len(matches)}"
        )

        # Must have detectSmartDirection taking textContent
        smart_dir_calls = re.findall(r"detectSmartDirection\([^)]*textContent[^)]*\)", content)
        assert len(smart_dir_calls) >= 8, (
            f"Expected at least 8 detectSmartDirection calls using textContent in patcher.py, found {len(smart_dir_calls)}"
        )

    def test_exclusive_text_content_in_patcher_js(self):
        """
        Verify that src/patcher.js uses .textContent across direction inspection points.
        """
        js_path = SRC_DIR / "patcher.js"
        content = js_path.read_text(encoding="utf-8")

        matches = re.findall(r"\.textContent\b", content)
        assert len(matches) >= 10, (
            f"Expected at least 10 occurrences of '.textContent' in src/patcher.js, found {len(matches)}"
        )

        smart_dir_calls = re.findall(r"detectSmartDirection\([^)]*textContent[^)]*\)", content)
        assert len(smart_dir_calls) >= 8, (
            f"Expected at least 8 detectSmartDirection calls using textContent in patcher.js, found {len(smart_dir_calls)}"
        )

    def test_python_generated_snippet_has_no_inner_text(self):
        """
        Verify that the runtime injection snippet generated by Python's get_injection_snippet()
        has zero instances of innerText and uses textContent exclusively.
        """
        snippet = patcher.get_injection_snippet()
        assert "innerText" not in snippet, "Generated injection snippet must not contain 'innerText'"
        assert "textContent" in snippet, "Generated injection snippet must contain 'textContent'"

    def test_no_busy_wait_spinlocks_in_patcher_js(self):
        """
        Verify that src/patcher.js contains no CPU-pegging busy-wait spinlocks like:
        while (Date.now() - start < ...) {}
        """
        js_path = SRC_DIR / "patcher.js"
        content = js_path.read_text(encoding="utf-8")

        # Check for while loop with Date.now
        spinlock_match = re.search(r"while\s*\(\s*Date\.now\(\)\s*-\s*\w+\s*<\s*\d+\s*\)\s*\{\s*\}", content)
        assert spinlock_match is None, (
            f"Found busy-wait spinlock in src/patcher.js: '{spinlock_match.group(0) if spinlock_match else ''}'"
        )

    def test_no_ping_sleep_loops_in_patcher_js(self):
        """
        Verify that src/patcher.js does not spawn external ping.exe subprocesses for sleep delays.
        """
        js_path = SRC_DIR / "patcher.js"
        content = js_path.read_text(encoding="utf-8")

        assert "ping 127.0.0.1" not in content, (
            "Found 'ping 127.0.0.1' subprocess invocation in src/patcher.js! "
            "Must use non-blocking / sync sleep instead of external ping."
        )
